### ISSUE TITLE
Example mismatch

### ISSUE THREAD

**Issue by ernewton** [shadden/TTV2Fast2Furious#1]
I used pip to install the package and separately downloaded the Example.ipynb file. I don't get identical results to what is displayed on the GitHub view of the ipython notebook. Attached is an image of the 2 planet TTV results that I get. I'm using python 3.7.3.
![image](https://user-images.githubusercontent.com/4790228/76448572-ef5d2e80-63a0-11ea-9b68-b2b17e7c4e51.png)

**Comment by shadden** [comment]
Hi Elisabeth--
 The mismatch is almost certainly due to the fact that the Examples.ipynb notebook randomly generates a pair of pomega values for the two planets (probably not smart on my part...).
See the line in the 3rd input cell:
   'varpi,varpi1 = np.random.uniform(0,2*np.pi,2)'
I'll go ahead and close this for now but feel free to raise any other issues!
